console.log("hello");
console.log("hello");
console.log("hello");
// let a = 12;

try {
    console.log(a);
}
catch(e) {
    console.log("caught an error...")
    console.log(e);
}

console.log("hello2");
console.log("hello2");
console.log("hello2");